### ISSUE TITLE
Cannot install from Repo + crash on LineageOS 19.1without GApps

### ISSUE THREAD

**Issue by pled** [zimbelstern/Tournant#1]
Hi,

Thank you for that app, it looks good to be able to use Gourmand recipes on android !

I faced two issues trying to install Tournant. 

1) I can add repo in F-Droid, retrieve the app in the lists, but cannot install. See repo.log attached.
2) After installing apk, importing my recipes (all this is ok), I got app to crash if I open any recipe. See crash.log attached.

I have to mention I am running non-official LineageOS 19.1 version **without GApps** installed. Is there any requirement about your application regarding Google Apps ??

Let me know if you need more information.

[crash.log](https://github.com/zimbelstern/Tournant/files/9445466/crash.log)
[repo.log](https://github.com/zimbelstern/Tournant/files/9445467/repo.log)

**Comment by pled** [comment]
Tried again with LineageOS 18.1 and microG service.
1) Still unable to install apk from f-droid : 
`09-02 17:29:59.696  2935  7851 W MirrorChooserImpl: io.ktor.client.plugins.ServerResponseException: Server error(GET https://zimbelstern.eu/fdroid/repo/tournant-1.1.apk: 500 . Text: ""
`
I can confirm https://zimbelstern.eu/fdroid/repo/tournant-1.1.apk returns `500 internal server error`.

2) Still crash at recipe opening.

**Comment by zimbelstern** [comment]
Hi,

thank you for filing this bug.

The misconfiguration of the repo server should be resolved by now.

Tournant does not depend on any non-free stuff and should run on pure AOSP and derived ROMs. I haven't installed Google Play Services either. :-)

After reading the logs, I assume that you are a more experienced cook who has more recipes than I have tested the app with. I am going to enlarge my cookbook for testing purposes and see what I can do from there. You can, however, give me a copy of your recipe file for testing, if you'd like.

Anyway, I keep you updated here.

**Comment by pled** [comment]
Here is my recipes file.
[All-recettes.zip](https://github.com/zimbelstern/Tournant/files/9487844/All-recettes.zip)
Regards.

**Comment by zimbelstern** [comment]
Thank you. I can preview your recipes with the bug fixed. I am confident to publish an updated version by the end of the week.
