### ISSUE TITLE
Recipes doesn't appear if no category exists

### ISSUE THREAD

**Issue by ArthurKlausHoff** [Zimbelstern/Tournant#13]
Recipes don't appear until you create one where the category field is not empty.

In the image bellow i created 2 recipes, they don't appear but are counted in the top bar:
![Screenshot_20230627-214304](https://github.com/Zimbelstern/Tournant/assets/57872111/ef672780-4079-4dd5-9b0c-4b337480e1bc)

When i create a recipe with a category they all appear:
![Screenshot_20230627-214316](https://github.com/Zimbelstern/Tournant/assets/57872111/8e25fbd8-2e88-41cc-85e3-a73c008633e1)

**Comment by Zimbelstern** [comment]
Hi, this should be solved now. Version 2.2.1 is available in my repository.
The next releases will probably be dedicated to bugfixes and small improvements. Feel free to point out what is not working.
