### ISSUE TITLE
order option

### ISSUE THREAD

**Issue by moolight-seashell** [Zimbelstern/Tournant#15]
on the main screen you may add an order and filter system

the filters already exist with the category, but is not a verry well ux

it will be better if we can have a filer button that show a popup near to full screen with a search bar ( for searching Categories )

When we create a new recipe it wil be a huge improvment if we can have suggestions about other categories in the database.
something like , the categorie in tbe database that may look like what you have written are : , with a count of hiw many time this category is used.

Back to the main screen, a order button with option like random, newest, oldest , faster, slower, ...) will be a huge improve

**Comment by Zimbelstern** [comment]
Many of these suggestions have been implemented in multiple commits over the last months. Maybe I will add some more complex filtering at some point in the future. For now, I think the order feature and other improvements make it easy to find the desired recipes. I call this one closed. :)
