### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Zimbelstern/Tournant#17]
...reproducible

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5231019614#L771

CI APK: https://gitlab.com/fdroid/fdroiddata/-/jobs/5231019614/artifacts/file/tmp/eu.zimbelstern.tournant_16.apk

Upstream APK: https://zimbelstern.eu/fdroid/repo/tournant-2.2.3.apk

Log looks like that other app: https://github.com/dessalines/thumb-key/issues/400#issuecomment-1729085573

The [other app updated to Gradle 8.3](https://github.com/dessalines/thumb-key/commit/301714a8e3b75de155189b234c66edde15c92bc9) and now it's reproducible, maybe they fixed something in the newer version?

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/6c337d8d6581123639091b01e8ef733fc616d2f3

**Comment by Zimbelstern** [comment]
It turned out that this is completely unrelated. Apparently, there were two problems: Tag v2.2.3 went astray, and #16. With the most recent commit 6cc151ebb47c1d78051235fcbc5927e781850139 fdroid builds the version 2.2.3 and verifies the binaries.

I have already forked F-Droid metadata repository on Gitlab for another app [which is stuck](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13756) and I don't know how to create another fork to change the commit in the metadata and solve this.

**Comment by licaon-kter** [comment]
You can delete your fork of fdroiddata, fork again, edit your .yml in a new branch (edit commit and remove disable line) then open MR from that.

**Comment by Zimbelstern** [comment]
What happens with the already opened merge request when I delete my fork?

**Comment by licaon-kter** [comment]
Thanks https://gitlab.com/fdroid/fdroiddata/-/commit/3a01d4effce29e593c9fcb552f421376be4ad781

**Comment by Zimbelstern** [comment]
Great to see a successful build again today.
If you have any time @licaon-kter, any help with [this non-reproducible one](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13756#note_1599407652) will be very appreciated. I probably won't get any step further with this.

**Comment by linsui** [comment]
It failed again. https://github.com/Zimbelstern/Tournant/blob/9d6cb471d6a3d04506bcefc50cfd13a339f6caa6/app/build.gradle.kts#L27 Please use rootProject instead of relative path to current dir. F-Droid runs gradle in app.

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/7915281150#L1795

**Comment by licaon-kter** [comment]
fixed in https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15828

**Comment by Zimbelstern** [comment]
I was prepared this time. ;-)

**Comment by licaon-kter** [comment]
hmmm  https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8394199526#L463

difflog: [tour27.log](https://github.com/user-attachments/files/17796834/tour27.log)

maybe you can clean cache and rebuild? attach the apk here, rename as ZIP (do not archive!)

**Comment by Zimbelstern** [comment]
Hi, thanks for the notice. I ran `./gradlew clean` and built again but it output the very same apk still differing from yours in these generated launcher png files.

**Comment by licaon-kter** [comment]
@Zimbelstern maybe one of those tricks would help? https://f-droid.org/docs/Reproducible_Builds/#png-crushcrunch

you can upload an APK here, rename as ZIP (do not archive!) and post the commit for us to test
