### ISSUE TITLE
[feat] ability to fine tune the number of portions/yield

### ISSUE THREAD

**Issue by serpico** [Zimbelstern/Tournant#18]
In Gourmet/Gourmand I'm used to play with/tinker the yield ( to match the amount of a specific ingredient I have while keeping all the other ratio in check ).

Afaik,  - + in tournant increase/decrease the amount by 1 ( from 4 portions in the recipe to 3 or 5 ) same goes when taping on the yield  which makes the numeric keypad appear but only the first digit is editable ( if original yield is 4,90 , I can have 3,90, 5,90 and so on...)

Is it possible to have all the digits editable ?

In Gourmet the smallest ( and default ) increment via +- seems to be 0,25 although if I type 4,68 then + and - the amount of ingredient is recalculated for 4,68 giving me the precision I was looking for.

Thanks for the app

Tournant 2.3.0 from F-droid
Android 6.0.1
Asus Zenfone Z010D

**Comment by Zimbelstern** [comment]
Hi,

this seems to be a bug. What do you mean when you say only the first digit is editable? Is it not possible to move the cursor behind the comma or are the changes not being reflected?

The increase/decrease buttons can't guess the user's intention so yes, I let them to just increase/decrease the amount by 1 in most cases. However, you should be able to change the amount in the input field to whatever decimal number you like. (The soft keyboard should show a comma in your case.)

There was a bug regarding this input field but I don't think that your problem is related.

**Comment by serpico** [comment]
Thanks for the follow up

As you wrote, it's not possible to move the cursor behind the comma ( although there's no comma as the UI use fraction i.e : 4 3/4 ), so let's behind the the first digit ( the 4 in my case )

You'll notice also on the screenshot 3/4 is kinda greyed out/lighter shade as opposed to the 4 which is black and underlined.

The cursor doesn't appear in the screenshot but was present behind the underlined 4 and blinking when I took it and when the input field is active.

![Screenshot_20231127-161123](https://github.com/Zimbelstern/Tournant/assets/1227077/269d8207-6997-4b9f-bc9e-5962f3365e4b)

**Comment by Zimbelstern** [comment]
Thanks for the screenshot, this explained a lot.

Gourmand exported the recipe yield in this way `<yields>4 3/4 parts</yields>` and when Tournant tried to extract a number, it took only `4` for the value and used `3/4 parts` for the yield unit. So basically it thinks that the yield of this recipe is 4. I will probably change that in the next release.

However, this won't change already imported recipes. But what you can do is: Go to edit, remove `3/4` from the right box and change the value in the left one to `4,75`.

Second problem: Aren't you able to insert a comma in the fields? I've tested the app on several devices and emulators  and on all of them, the popup keyboard shows a button for a comma. Are you using the default keyboard of your device or a different one?

PS: Do you know you can long tap on an ingredient? I use this sometimes to adjust the recipe amount to fit the exact weight of the eggs.

**Comment by serpico** [comment]
About the workaround you proposed and the second problem, unfortunately to display a comma I have to press/tap on the blue button at the bottom right of the keyboard ( shown in my screenshot ) "Suivant" then an extended/full keyboard appears but at the same time the cursor jump to the right and goes into the right box, so impossible to get the comma into the left box that way, and change the value to `4,75`.

As far as I know it's the default keyboard of the device ( but the phone was reinstalled with the original rom so who knows maybe something is missing...), to be accurate on edit mode, if I tap on a box filled with letters ( like title, category, instructions, notes....) the full keyboard with all the letters, numbers and further access to punctuation signs including comma appears but on the boxes with the amount of ingredients, prep time, cooking time, and the yield number only a limited keyboard as shown in my previous screenshot appears.

The only workaround I found to get `4,75` in the left box is to type at least the comma in a box that trigger the full keyboard and then cut/paste it inside the left box. after that I can change the decimals as I please and obtain the recalculation of the amounts of ingredients as expected.

**Comment by Zimbelstern** [comment]
The input fields where the user is supposed to enter numbers are set to input type `TYPE_CLASS_NUMBER` with flag `TYPE_NUMBER_FLAG_DECIMAL`. The system and the keyboard are expected to follow and allow the input of a decimal number. Apparently, your keyboard does not handle this correctly.

This means that I can not do anything about it, sorry. The keyboard is out of the area of direct influence of my app. I can try to fine tune some things and see if it changes the behaviour of your keyboard app. Could you tell me the name of your keyboard and which ROM you are using? I installed some other keyboard apps from F-Droid but they all seemed to work.

**Comment by serpico** [comment]
Sorry for the delay, I didn't get what you meant about scaling via long tap/press on one ingredient and change the amount to recalculate all the other ingredients accordingly but I do now. Since it the `,` issue most probably comes from my phone I'll close the issue. Thanks for taking the time and looking into it
