### ISSUE TITLE
Timer launch from within the recipe not working starting 2.6.0

### ISSUE THREAD

**Issue by serpico** [Zimbelstern/Tournant#20]
Android 6.0.1

After upgrading to 2.7.0 I noticed a previous neat feature, i.e whenever the user tap on a duration embedded ( the duration(s) appears as a blue link in the instructions section starting 2.4.0 - no special formatting in 2.3.0 as far as I can tell ) in the recipe it launches a timer for the said duration, had disappeared. In 2.7.0 the same action just "dim" the paragraph as to indicate the step has been completed, but no timer launch.

I uninstalled and tried older versions to see if I have dreamed this feature :) but it was indeed present on 2.4.0 ( 2.5.0, 2.5.1 would crash as soon as I tried to open a recipe on my phone ).

In 2.6.0 the blue link is still there but tapping on it would just "dim" the paragraph, not starting a timer.
In 2.7.0 the behavior is the same as far as I can tell ( "diming" - no timer ).

Thanks

**Comment by Zimbelstern** [comment]
The expected behaviour is now that a dialog opens which lets you adjust the time before setting the timer.
It seems to work on my emulator devices running Android 5 and Android 8. Maybe, The problem is with Android 6 only? I'll try to find out more.

**Comment by uli-on** [comment]
Works as expected on android 13, BTW, and I'm really happy that i don't need an extra app for it. Thanks! ☺️
