### ISSUE TITLE
Yield calculations stop at 4

### ISSUE THREAD

**Issue by reujab** [Zimbelstern/Tournant#24]
Hey, awesome app. I noticed a very strange bug where yield calculations stop at 4 servings if the amount is exactly 0.58. To reproduce this bug, create a recipe with 0.58 of anything and 0.579 of anything. Note that when changing the yield from 1 lot to 4 lots, the measurement of 0.58*4 is wrong, while the measurement of 0.579 is correct.

![Screenshot_20241028-180054](https://github.com/user-attachments/assets/1a6f1e05-5940-4621-a54a-a4a842d5cb54)

![Screenshot_20241028-180124](https://github.com/user-attachments/assets/fe916776-46b7-40b4-af63-e4099ef71142)

**Comment by Zimbelstern** [comment]
Crazy. :D
