### ISSUE TITLE
cannot change language manually

### ISSUE THREAD

**Issue by Pochulasky** [Zimbelstern/Tournant#26]
pic related:
I cannot change to my mother language (chinese simplified)
![Imagepipe_81](https://github.com/user-attachments/assets/5fc8c27b-c930-48a7-b6fc-103e8eec2650)

**Comment by Zimbelstern** [comment]
Hi, could you please provide the following data?
– Android version
– System language
– Open the Android preferences, go to app list and select Tournant: Can you change the language there (depends on Android version)?
Thank you.

**Comment by Pochulasky** [comment]
I have 2 phone. this is the phone I'm using. after a few hours I will give answer with another phone
– Android 13
– Chinese Simplified
– no. cannot set language invidually (another phone can)

**Comment by Zimbelstern** [comment]
Apparently, the value of the gradle property `projectDir` had changed.
