### ISSUE TITLE
Tournant crashes when recipe will be displayed

### ISSUE THREAD

**Issue by fsand1** [zimbelstern/Tournant#4]
I installed Tournant and could import my recipes from Gourmand. No problem.
But when I will open any recipe, the recipe will be shown for a second and then the system crashes. The same happens when I try to open "Einstellungen" or "Über Tournant".
First impression is very good in terms of parsing the xml-file from Gourmand. Can you please fix the problem.
I am using OnePlus with Android 12.
Best regards, Frank

**Comment by zimbelstern** [comment]
Hi,
thank you for submitting this issue.
Do you have version 1.1.1 installed? I can not reproduce the crash on Android 12. You could help with the diagnosis if you could provide a logcat output of the crash and/or attach the problematic recipe file.

**Comment by fsand1** [comment]
Hi,
Installed today the most recent version 1.1.2.
Works excellent!!!
Thank you very much.
Best regards, Frank
