### ISSUE TITLE
Tournant does not display Ingredient-lists correctly when Ingredient-groups have been used

### ISSUE THREAD

**Issue by fsand1** [zimbelstern/Tournant#7]
When you use  "inggroup.../inggroup" to make a ingredients-list better readable, structured and usable, Tournant does not display the content of  the groups.

**Comment by zimbelstern** [comment]
I've never noticed ingredient groups in Gourmand so could you provide
a) a screenshot how they look like in Gourmand
b) the corresponding recipe file (or relevant section)
? That would speed things up because Gourmand is broken in Debian testing right now (well, at least on my machine).

**Comment by fsand1** [comment]
![Bildschirmfoto vom 2022-10-23 10-27-58](https://user-images.githubusercontent.com/113342522/197382509-3bdb818b-59dc-4528-8549-d13f6328d509.png)
[Flusskrebsmousse.txt](https://github.com/zimbelstern/Tournant/files/9846027/Flusskrebsmousse.txt)

Sorry for some Typos in the German recipe text. Please disregard them.

The same behaviour of Tournant will happen when a recipe is constructed out of multiple recipes. Even the actual GOURMAND version (I am running Linux Mint 21 Cinnamon with GOURMAND 1.0.0-7) does not show the real content of the recipes. The old GOURMET version did it properly at least in printing. I attached the xml-code for this "problem" as well.

![Bildschirmfoto vom 2022-10-23 10-49-24](https://user-images.githubusercontent.com/113342522/197383165-d86460b2-ffbc-43d0-9471-6f3b3d715e2b.png)
[Hummercannelloni auf Fenchelgemüse mit kandierter Ananas und Hummerschaum.txt](https://github.com/zimbelstern/Tournant/files/9846054/Hummercannelloni.auf.Fenchelgemuse.mit.kandierter.Ananas.und.Hummerschaum.txt)

I think in Tournant it would make sense to list the links for the sup-recipes to directly jump to like it is implemented in the actual version of GOURMAND.
I had to rename the xml-files to txt for uploading. Hope it will help you.
Sorry for spoiling your weekend.

**Comment by zimbelstern** [comment]
Ah, I see. Ingredient groups are a useful feature indeed.
It will not be very difficult to implement these two features in Tournant but as it requires modifications in several classes I will not promise to get it done in October. :)

**Comment by zimbelstern** [comment]
Ah, I see. Ingredient groups are a useful feature indeed.
It will not be very difficult to implement these two features in Tournant but as it requires modifications in several classes I will not promise to get it done in October. :)

**Comment by zimbelstern** [comment]
Ah, I see. Ingredient groups are a useful feature indeed.
It will not be very difficult to implement these two features in Tournant but as it requires modifications in several classes I will not promise to get it done in October. :)

**Comment by fsand1** [comment]
Sorry, but after installing the new version 1.1.2 I could not recognize any changes in presentation.
